# Generated by Django 3.0.2 on 2020-01-11 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0006_auto_20180328_1430'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='year_in_school',
            field=models.CharField(choices=[('FR', 'Freshman'), ('SO', 'Sophomore'), ('JR', 'Junior'), ('SR', 'Senior'), ('GR', 'Graduate')], default='FR', max_length=2),
        ),
        migrations.AlterField(
            model_name='article',
            name='content',
            field=models.CharField(max_length=1000, null=True, verbose_name='Yorumunuz.. (En fazla 1000 karakter)'),
        ),
    ]
