# Generated by Django 3.0.2 on 2020-01-11 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0007_auto_20200111_1612'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='year_in_school',
        ),
        migrations.AddField(
            model_name='article',
            name='article_image_c',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Makaleye Cevap Fotoğrafı Ekleyin'),
        ),
    ]
