# Generated by Django 3.0.2 on 2020-01-12 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0008_auto_20200111_1843'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebSite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('üyeliksistem', models.BooleanField(default=True)),
            ],
        ),
        migrations.AlterField(
            model_name='article',
            name='article_image',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Soru Fotoğrafı Ekleyin'),
        ),
        migrations.AlterField(
            model_name='article',
            name='article_image_c',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Cevap Fotoğrafı Ekleyin'),
        ),
    ]
